import React, { PureComponent } from 'react';
import { Row, Col, DatePicker, Button } from 'antd';
import { connect } from 'umi';
import moment from 'moment';
import styles from './index.less';

const dateFormat = 'YYYY/MM/DD';

@connect(({ offboarding: { myRequest = {} } = {} }) => ({
  myRequest,
}))
class RequestChangeLWD extends PureComponent {
  render() {
    const { myRequest: { lastWorkingDate = '' } = {} } = this.props;
    const dateValue = moment(lastWorkingDate).format('YYYY/MM/DD');
    return (
      <div className={styles.viewChangeLastWorkingDay}>
        <p className={styles.viewChangeLastWorkingDay__title}>Resignation request details</p>
        <p className={styles.viewChangeLastWorkingDay__label}>
          Last working day (generated by system)
        </p>
        <Row className={styles.viewChangeLastWorkingDay__viewDateApproved} gutter={[50, 0]}>
          <Col span={8}>
            <DatePicker
              value={dateValue && moment(dateValue, dateFormat)}
              format={dateFormat}
              className={styles.viewChangeLastWorkingDay__viewDateApproved__datePicker}
              disabled
            />
          </Col>
          <Col span={16} className={styles.viewChangeLastWorkingDay__viewDateApproved__description}>
            <span className={styles.viewChangeLastWorkingDay__viewDateApproved__description__text1}>
              A last working date (LWD) is generated as per a 90 days notice period according to our{' '}
            </span>
            <span className={styles.viewChangeLastWorkingDay__viewDateApproved__description__text2}>
              Standard Resignation Policy
            </span>
          </Col>
        </Row>
        <Button
          // onClick={this.onClickNext}
          className={styles.viewChangeLastWorkingDay__button}
        >
          Extend or shorten LWD
        </Button>
      </div>
    );
  }
}

export default RequestChangeLWD;
