import React, { Component, Fragment } from 'react';
import { Row, Col, DatePicker, Button } from 'antd';
import ModalRequestChangeLWD from '@/components/ModalRequestChangeLWD';
import { connect } from 'umi';
import moment from 'moment';
import styles from './index.less';

const dateFormat = 'YYYY/MM/DD';

@connect(({ offboarding: { myRequest = {} } = {}, loading }) => ({
  myRequest,
  loading: loading.effects['offboarding/requestChangeLWD'],
}))
class RequestChangeLWD extends Component {
  constructor(props) {
    super(props);
    this.state = {
      visible: false,
      keyModal: '',
    };
  }

  handleModal = () => {
    const { visible } = this.state;
    this.setState({
      visible: !visible,
      keyModal: !visible ? '' : Date.now(),
    });
  };

  submitRequest = (values) => {
    const { dispatch, myRequest: { _id: id = '' } = {} } = this.props;
    const payload = { id, ...values };
    dispatch({
      type: 'offboarding/requestChangeLWD',
      payload,
    }).then(({ statusCode }) => {
      if (statusCode === 200) {
        this.handleModal();
      }
    });
  };

  render() {
    const { myRequest: { lastWorkingDate = '' } = {}, loading } = this.props;
    const { visible, keyModal } = this.state;
    const dateValue = moment(lastWorkingDate).format('YYYY/MM/DD');
    return (
      <Fragment>
        <div className={styles.viewChangeLastWorkingDay}>
          <p className={styles.viewChangeLastWorkingDay__title}>Resignation request details</p>
          <p className={styles.viewChangeLastWorkingDay__label}>
            Last working day (generated by system)
          </p>
          <Row className={styles.viewChangeLastWorkingDay__viewDateApproved} gutter={[50, 0]}>
            <Col span={8}>
              <DatePicker
                value={dateValue && moment(dateValue, dateFormat)}
                format={dateFormat}
                className={styles.viewChangeLastWorkingDay__viewDateApproved__datePicker}
                disabled
              />
            </Col>
            <Col
              span={16}
              className={styles.viewChangeLastWorkingDay__viewDateApproved__description}
            >
              <span
                className={styles.viewChangeLastWorkingDay__viewDateApproved__description__text1}
              >
                A last working date (LWD) is generated as per a 90 days notice period according to
                our{' '}
              </span>
              <span
                className={styles.viewChangeLastWorkingDay__viewDateApproved__description__text2}
              >
                Standard Resignation Policy
              </span>
            </Col>
          </Row>
          <Button onClick={this.handleModal} className={styles.viewChangeLastWorkingDay__button}>
            Extend or shorten LWD
          </Button>
        </div>
        <ModalRequestChangeLWD
          loading={loading}
          visible={visible}
          key={keyModal}
          handleCancel={this.handleModal}
          handleSubmit={this.submitRequest}
        />
      </Fragment>
    );
  }
}

export default RequestChangeLWD;
