# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy-prod

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - production-runner
  script:
    - source /etc/environment
    - whoami
    - uname -a
    - npm install
    - npm run build
    - docker login -u khoa.le -p $PWD gitlab.paxanimi.ai:8150
    #- docker rmi gitlab.paxanimi.ai:8150/hrms/hrms-frontend:latest
    - docker build -t gitlab.paxanimi.ai:8150/hrms/hrms-frontend:latest -f Dockerfile .
    - docker push gitlab.paxanimi.ai:8150/hrms/hrms-frontend:latest
    - kubectl delete -f /home/frontend/frontend-deployment.yaml
  only:
    - production

deploy-job-prod:
  stage: deploy-prod
  tags:
    - production-runner
  script:
    - kubectl apply -f /home/HRMS-microservices/frontend/frontend-deployment.yaml
  only:
    - production
