export const AVAILABLE_STATUS = {
  AVAILABLE_NOW: 'Available Now',
  AVAILABLE_SOON: 'Available Soon',
};

export const RESOURCE = {
  MODAL_TYPE: {
    EDIT: 'EDIT',
    ADD: 'ADD',
    HISTORY: 'HISTORY',
    WARN: 'WARN',
    MANAGER_CHANGE: 'MANAGER_CHANGE',
    ASSIGN_SUCCESS: 'ASSIGN_SUCCESS',
    ADD_COMMENT: 'ADD_COMMENT',
    EDIT_COMMENT: 'EDIT_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    VIEW_COMMENT: 'VIEW_COMMENT',
  },
};
