

describe('customer management', () =>{
    before( () => {
        cy.visit('https://stghrms.paxanimi.ai/login');
        cy.login('sandeep@mailinator.com','12345678@Tc')
    });
    it('customer management', () =>{
        cy.contains('Customer Management').click({force:true});
        cy.wait(5000)
        // cy.scrollTo('bottom').wait(2000)
        // cy.get('[type="button"]').eq(3).click({force:true})
        // cy.get('[type="button"]').eq(2).click({force:true})
        // cy.scrollTo('top').wait(2000)
        cy.contains('10101').click({force:true});
         /////contact info
        //  cy.get('.contactInfoHeaderTitle___1qi6s').should('have.text','Contact Info')
         cy.wait(5000)
         cy.contains('Edit').click({force:true})
         cy.wait(2000)
         cy.get('#myForm_addressLine2').type('poiuyt')
         cy.wait(2000)
         cy.contains('Update').click({force:true})
         cy.wait(2000)
         /////Divisions
         cy.contains('Divisions').click({force:true})
         cy.wait(5000)
         // cy.get('.contactInfoHeaderTitle___2HMgf').should('have.text','test division company')
         cy.wait(2000)
         cy.contains('Edit').click({force:true})
         cy.wait(5000)
         cy.get('#formEdit_comments').type('am a good customer')
         cy.wait(2000)
         cy.contains('Save Changes').click({force:true})
         cy.wait(3000)
         cy.contains(' View More').click({force:true})
         cy.wait(2000)
         cy.contains(' View less').click({force:true})
         cy.wait(2000)
         cy.contains('Add another Division').click({force:true})
         cy.wait(1000)
         cy.get('#formAdd_divisionName').type('division2')
         cy.wait(2000)
         cy.get('#formAdd_primaryPOCName').type('terralogic')
         cy.wait(2000)
         cy.get('#formAdd_primaryPOCPhNo').type('9502985552')
         cy.wait(2000)
         cy.get('#formAdd_primaryPOCEmail').type('metta@gmail.com')
         cy.wait(2000)
         cy.get('#formAdd_primaryPOCDesignation').type('CEO Of INDIA')
         cy.wait(2000)
         cy.get('#formAdd_comments').type('please add my division')
         cy.wait(2000)
         cy.get('[form="formAdd"]').click({force:true})
         cy.wait(2000)
         ////DOCUMENTS
         cy.contains('Documents').click({force:true})
         cy.wait(5000)
         cy.contains('Add Document').click({force:true})
         cy.wait(3000)
         cy.get('.ant-select-selector').click({force:true})
         cy.wait(2000)
         cy.get('.ant-select-item-option-content').eq(4).click({force:true})
         cy.wait(2000)
         cy.get('#addDoc_documentName').type('ACN')
         cy.wait(2000)
         cy.get('#addDoc_comments').type('just to check the comment section is working or not')
         cy.wait(2000)
         const image = 'ADSA.pdf';
         cy.get('input[type="file"]').attachFile(image);
         cy.wait(3000)
         cy.get('[form="addDoc"]').click({force:true})
         cy.wait(2000)
         cy.contains('Filter').click({force:true})
         cy.wait(5000)
         cy.get('#filter_byType').click({force:true})
         cy.wait(2000)
         cy.get('.ant-select-item-option-content').eq(4).click({force:true})
         cy.wait(2000)
         cy.contains('Apply').click({force:true})
         cy.wait(2000)
         cy.contains('Close').click({force:true})
         cy.wait(3000)
         cy.contains('Filter').click({force:true})
         cy.wait(5000)
         cy.get('#filter_byType')
         cy.get('.ant-select-clear').eq(0).click({force:true})
         cy.wait(2000)
         cy.get('#filter_byCompany').click({force:true})
         cy.get('.ant-select-item-option-content').eq(5).click({force:true})
         cy.wait(2000)
         cy.contains('Apply').click({force:true})
         cy.wait(2000)
         cy.contains('Close').click({force:true})
         cy.wait(3000)
         cy.contains('Filter').click({force:true})
         cy.wait(5000)
         cy.get('#filter_byCompany')
         cy.get('.ant-select-clear').click({force:true})
         cy.wait(2000)
         cy.get('#filter_fromDate').type('Apr 22, 2022'+'{enter}',{force:true})
         cy.wait(3000)
         cy.get('#filter_toDate').type('Apr 29, 2022'+'{enter}',{force:true})
         cy.wait(3000)
         cy.contains('Apply').click({force:true})
         cy.wait(2000)
         cy.contains('Close').click({force:true})
         cy.wait(3000)
         cy.get('[placeholder="Search by Document Type"]').type('OTHER')
         cy.wait(3000)
         //NOTES
         cy.contains('Notes').click({force:true})
         cy.wait(3000)
         cy.get('#note.ant-input').type('hiii team,how are you all')
         cy.wait(2000)
         cy.contains('Add notes').click({force:true})
         cy.wait(2000)
         cy.contains('Filter').click({force:true})
         cy.wait(2000)
         cy.get('#filter_byAuthor').click({force:true})
         cy.wait(2000)
         cy.get('.ant-select-item-option-content').eq(0).click({force:true})
         cy.wait(1000)
         cy.contains('Apply').click({force:true})
         cy.wait(2000)
         cy.contains('Close').click({force:true})
         cy.wait(2000)
         cy.contains('Filter').click({force:true})
         cy.wait(2000)
         cy.get('#filter_byAuthor')
         cy.get('.ant-select-arrow').eq(0).click({force:true})
 
 
 
         cy.get('#filter_fromDate').type('Apr 27, 2022'+'{enter}',{force:true})
         cy.wait(2000)
         cy.get('#filter_toDate').type('Apr 28, 2022'+'{enter}',{force:true})
         cy.wait(2000)
         cy.contains('Apply').click({force:true})
         cy.wait(2000)
         cy.contains('Close').click({force:true})
         cy.wait(2000)
         cy.get('[placeholder="Search by Key Words"]').type('team'+'{enter}')
         cy.wait(2000)
         //AUDIT TRAILS
         cy.contains('Audit Trail').click({force:true})
         cy.wait(3000)
 

        cy.wait(5000)
        cy.contains('Customer Management').click({force:true});
        cy.wait(8000)
        cy.contains('Kai Thị Hoàng Linh').trigger('mouseover', {force:true}).wait(2000);
        // cy.contains('View full profile').click();
        cy.get('.closeButton___3cknv').click({force:true})
        cy.contains('Add new customer').click({force:true})
        cy.add('Raju','lollypop','9502985592','raju@terralogic.com','3-104','chittoor','chii','51712')
        cy.wait(2000)
        cy.add1('Yen Yen')
        cy.wait(3000)
        cy.contains('Filter').click();
        cy.add_customer('Yen Yen')
        cy.wait(2000)
        cy.contains('Settings').click({force:true})
    })
    
});
