const BASE_API_DEV = 'https://stghrms.paxanimi.ai';
const BASE_API_PRODUCTION = 'https://hrms.paxanimi.ai';

export const API_KEYS = {
  BASE_API: 'BASE_API',
  TIMESHEET_API: 'TIMESHEET_API',
  PROJECT_API: 'PROJECT_API',
  TICKET_API: 'TICKET_API',
  CUSTOMER_API: 'CUSTOMER_API',
};

export const proxy = {
  dev: {
    [API_KEYS.BASE_API]: BASE_API_DEV,
    [API_KEYS.TIMESHEET_API]: BASE_API_DEV + '/timesheet',
    [API_KEYS.PROJECT_API]: BASE_API_DEV,
    [API_KEYS.TICKET_API]: BASE_API_DEV,
    [API_KEYS.CUSTOMER_API]: BASE_API_DEV,
  },
  prod: {
    [API_KEYS.BASE_API]: BASE_API_PRODUCTION,
    [API_KEYS.TIMESHEET_API]: BASE_API_PRODUCTION + '/timesheet',
    [API_KEYS.PROJECT_API]: BASE_API_PRODUCTION,
    [API_KEYS.TICKET_API]: BASE_API_PRODUCTION,
    [API_KEYS.CUSTOMER_API]: BASE_API_PRODUCTION,
  },
};
