export default [
  {
    path: '/login',
    component: '../layouts/SignupLayout',
    routes: [{ path: '/login/', component: './Login/index' }],
  },
  {
    path: '/password/reset/:code',
    component: '../layouts/SignupLayout',
    routes: [{ path: '/password/reset/:code(\\d+)', component: './ResetPassword/index' }],
  },
  {
    path: '/change-password',
    component: '../layouts/SignupLayout',
    routes: [{ path: '/change-password/', component: './ChangePassword/index' }],
  },
  {
    path: '/sub-forgot-password',
    component: '../layouts/SignupLayout',
    routes: [{ path: '/sub-forgot-password/', component: './SubForgotPassWord/index' }],
  },
  {
    path: '/forgot-password',
    component: '../layouts/SignupLayout',
    routes: [{ path: '/forgot-password/', component: './ForgotPassword/index' }],
  },
  {
    path: '/terms-and-conditions',
    component: '../layouts/TermsLayout',
    routes: [{ path: '/terms-and-conditions/', component: './TermsAndConditions/index' }],
  },
  {
    path: '/privacy-policy',
    component: '../layouts/TermsLayout',
    routes: [{ path: '/privacy-policy/', component: './PrivacyPolicy/index' }],
  },
  {
    path: '/signup',
    name: 'signup',
    component: '../layouts/SignupLayout',
    routes: [{ path: '/signup/', component: './Signup/index' }],
  },
  {
    path: '/videos-demo',
    component: '../layouts/VideosDemoLayout',
    routes: [
      {
        path: '/videos-demo/',
        name: 'Add A New Expense',
        redirect: '/videos-demo/webapp/addanewexpense',
      },
      {
        path: '/videos-demo/webapp',
        name: 'Add A New Expense',
        redirect: '/videos-demo/webapp/addanewexpense',
      },
      {
        path: '/videos-demo/webapp/addanewexpense',
        name: 'Add A New Expense',
        component: './VideosDemo/WebApp/AddNewExpense',
      },
      {
        path: '/videos-demo/webapp/addanewmileage',
        name: 'Add A New Mileage',
        component: './VideosDemo/WebApp/AddNewMileage',
      },
      {
        path: '/videos-demo/webapp/deleteupdateexpense',
        name: 'Delete Update An Expense',
        component: './VideosDemo/WebApp/DeleteUpdateExpense',
      },
      {
        path: '/videos-demo/webapp/addanewreport',
        name: 'Add A New Report',
        component: './VideosDemo/WebApp/AddNewReport',
      },
      {
        path: '/videos-demo/webapp/approveareport',
        name: 'Approve A Report',
        component: './VideosDemo/WebApp/ApproveAReport',
      },
      {
        path: '/videos-demo/webapp/commentareport',
        name: 'Comment A Report',
        component: './VideosDemo/WebApp/CommentAReport',
      },
      {
        path: '/videos-demo/webapp/askformoreinfo',
        name: 'Ask For More Info A Report',
        component: './VideosDemo/WebApp/AskForMoreInfoAReport',
      },
      {
        path: '/videos-demo/webapp/rejectareport',
        name: 'Reject A Report',
        component: './VideosDemo/WebApp/RejectAReport',
      },
      // Start mobile
      {
        path: '/videos-demo/mobile',
        name: 'Add A New Expense',
        redirect: '/videos-demo/mobile/add-a-new-expense',
      },
      {
        path: '/videos-demo/mobile/add-a-new-expense',
        name: 'Add A New Expense',
        component: './VideosDemo/Mobile/AddNewExpense',
      },
      {
        path: '/videos-demo/mobile/add-a-new-mileage',
        name: 'Add A New Mileage',
        component: './VideosDemo/Mobile/AddNewMileage',
      },
      {
        path: '/videos-demo/mobile/delete-update-expense',
        name: 'Delete Update An Expense',
        component: './VideosDemo/Mobile/DeleteUpdateExpense',
      },
      {
        path: '/videos-demo/mobile/add-a-new-report',
        name: 'Add A New Report',
        component: './VideosDemo/Mobile/AddNewReport',
      },
      {
        path: '/videos-demo/mobile/approve-a-report',
        name: 'Approve A Report',
        component: './VideosDemo/Mobile/ApproveAReport',
      },
      {
        path: '/videos-demo/mobile/comment-a-report',
        name: 'Comment A Report',
        component: './VideosDemo/Mobile/CommentAReport',
      },
      {
        path: '/videos-demo/mobile/reject-a-report',
        name: 'Reject A Report',
        component: './VideosDemo/Mobile/RejectAReport',
      },
      {
        component: '404',
      },
    ],
  },
  {
    path: '/question-and-answer',
    component: '../layouts/QALayout',
    routes: [
      {
        path: '/question-and-answer/',
        name: 'User Role',
        redirect: '/question-and-answer/webapp/howtologin',
      },
      {
        path: '/question-and-answer/webapp',
        name: 'User Role',
        redirect: '/question-and-answer/webapp/howtologin',
      },
      {
        path: '/question-and-answer/webapp/howtologin',
        name: 'How To Login?',
        component: './Q&A/WebApp/HowToLogin/index',
      },
      {
        path: '/question-and-answer/webapp/addinganewexpense',
        name: 'Adding A New Expense',
        component: './Q&A/WebApp/NewExpense/index',
      },
      {
        path: '/question-and-answer/webapp/addingamileageexpense',
        name: 'Adding A New Mileage Expense',
        component: './Q&A/WebApp/NewMileageExpense/index',
      },
      {
        path: '/question-and-answer/webapp/addingnewreport',
        name: 'Adding A New Report',
        component: './Q&A/WebApp/NewReport/index',
      },
      {
        path: '/question-and-answer/webapp/approvingrejectingareport',
        name: 'Approving/Rejecting A Report',
        component: './Q&A/WebApp/ApprovingRejectingReport/index',
      },
      {
        path: '/question-and-answer/webapp/commentingonareport',
        name: 'Commenting On A Report',
        component: './Q&A/WebApp/CommentReport/index',
      },
      {
        path: '/question-and-answer/webapp/exportingreports',
        name: 'Exporting Reports',
        component: './Q&A/WebApp/ExportingReport/index',
      },
      {
        path: '/question-and-answer/webapp/userprofile',
        name: 'User Profile',
        component: './Q&A/WebApp/UserProfile/index',
      },
      {
        path: '/question-and-answer/mobileapp/installandroid',
        name: 'How To Install The Android App',
        component: './Q&A/MobileApp/InstallAndroid/index',
      },
      {
        path: '/question-and-answer/mobileapp/installIOS',
        name: 'How To Install The IOS App',
        component: './Q&A/MobileApp/InstallIOS/index',
      },
      {
        path: '/question-and-answer/mobileapp/reinstallIOS',
        name: 'How To Reinstall The IOS App',
        component: './Q&A/MobileApp/ReinstallIOS/index',
      },
      {
        path: '/question-and-answer/mobileapp/howtologinMobile',
        name: 'How To Login?',
        component: './Q&A/MobileApp/HowToLogin/index',
      },
      {
        path: '/question-and-answer/mobileapp/newexpenseMobile',
        name: 'Adding A New Expense',
        component: './Q&A/MobileApp/NewExpense/index',
      },
      {
        path: '/question-and-answer/mobileapp/newmileageexpenseMobile',
        name: 'Adding A New Mileage Expense',
        component: './Q&A/MobileApp/NewMileage/index',
      },
      {
        path: '/question-and-answer/mobileapp/newreportMobile',
        name: 'Adding A New Report',
        component: './Q&A/MobileApp/NewReport/index',
      },
      {
        path: '/question-and-answer/mobileapp/approvalrejectreportMobile',
        name: 'Approving/Rejecting A Report',
        component: './Q&A/MobileApp/ApprovalRejectReport/index',
      },
      {
        path: '/question-and-answer/mobileapp/commentingreportMobile',
        name: 'Commenting On A Report',
        component: './Q&A/MobileApp/CommentingReport/index',
      },
      {
        path: '/question-and-answer/mobileapp/userprofileMobile',
        name: 'User Profile',
        component: './Q&A/MobileApp/UserProfile/index',
      },
      {
        component: '404',
      },
    ],
  },

  {
    path: '/',
    Routes: ['src/pages/Authorized'],
    component: '../layouts/BasicLayout',
    authority: ['admin', 'user', 'finance', 'customer', 'employee'],
    routes: [
      {
        path: '/',
        name: 'dashboard',
        icon: '/assets/new-imgs/window.svg',
        component: './Dashboard/index',
        hideInMenu: true,
        redirect: '/dashboard',
      },
      {
        path: '/admin',
        name: 'manage',
        authority: ['admin'],
        position: 'right-menu',
        icon: 'setting',
        hideInBreadcrumb: true,
        redirect: '/admin/location/active',
      },
      {
        path: '/profile',
        name: 'profile',
        position: 'right-menu',
        icon: '/assets/new-imgs/profile.svg',
        component: './Profile/index',
      },
      {
        path: '/expense/newmileage',
        name: 'mileage',
        position: 'right-menu',
        icon: 'user',
        component: './Mileage/AddNew/index',
      },
      {
        path: '/expense/updatemileage/:reId',
        name: 'Edit Mileage',
        hideInMenu: true,
        hideInBreadcrumb: true,
        component: './Mileage/AddNew/index',
      },
      {
        path: '/dashboard',
        name: 'dashboard',
        icon: '/assets/new-imgs/window.svg',
        component: './Dashboard/index',
        hideInBreadcrumb: true,
      },
      {
        path: '/profile',
        name: 'profile',
        icon: '/assets/new-imgs/profile.svg',
        component: './Profile/index',
      },
      {
        path: '/expense',
        name: 'bill.list',
        icon: '/assets/new-imgs/wallet.svg',
        hideInBreadcrumb: true,
        component: './Expense/index',
      },
      {
        path: '/report',
        name: 'Reports',
        icon: '/assets/new-imgs/report.svg',
        hideInBreadcrumb: true,
        component: './Report/index',
      },
      {
        path: '/teamreport',
        name: 'teamreport',
        isBottomMenu: true,
        icon: '/assets/new-imgs/group.svg',
        component: './TeamReport/index',
      },
      {
        path: '/payment',
        name: 'Payments',
        isBottomMenu: true,
        icon: '/assets/img/currencies.svg',
        component: './Payment/index',
      },
      {
        path: '/teamreport/view/:reId',
        hideInBreadcrumb: true,
        hideInMenu: true,
        name: 'viewReport',
        component: './Reimbursement/ViewReport/index',
      },
      {
        path: '/report/:type(request)',
        name: 'reimbursement.request',
        hideInMenu: true,
        component: './Reimbursement/index',
      },
      {
        path: '/report/:type(approval)',
        name: 'reimbursement.approval',
        hideInMenu: true,
        component: './Reimbursement/index',
      },
      {
        path: '/report/:type(pending)',
        name: 'reimbursement.pending',
        hideInMenu: true,
        component: './Reimbursement/index',
      },
      {
        path: '/report/:type(history)',
        hideInMenu: true,
        component: './Reimbursement/index',
      },
      {
        path: '/report/:action(add)',
        name: 'new',
        icon: 'plus',
        hideInMenu: true,
        component: './Reimbursement/New',
      },
      {
        path: '/report/:action(update)/:reId(\\d+)',
        name: 'update',
        icon: 'edit',
        hideInMenu: true,
        component: './Reimbursement/New',
      },

      {
        path: '/expense/:type(mileage|travel|non-travel)/:action(add)',
        name: 'new',
        hideInMenu: true,
        component: './Expense/NewBill',
      },
      {
        path: '/expense/:type(mileage|travel|non-travel)/:action(\\d+)',
        name: 'update',
        hideInMenu: true,
        component: './Expense/NewBill',
      },
      {
        path: '/expense/newexpense',
        name: 'Add New Expense',
        hideInMenu: true,
        hideInBreadcrumb: true,
        component: './Expense/components/NewExpenseForm/index',
      },
      {
        path: '/expense/update/:reId',
        name: 'Edit Expense',
        hideInMenu: true,
        hideInBreadcrumb: true,
        component: './Expense/components/NewExpenseForm/index',
      },
      {
        path: '/report/new',
        name: 'addnewreport',
        hideInBreadcrumb: true,
        hideInMenu: true,
        component: './Reimbursement/AddNewReport/index',
      },
      {
        path: '/report/view/:reId',
        hideInBreadcrumb: true,
        hideInMenu: true,
        name: 'viewReport',
        component: './Reimbursement/ViewReport/index',
      },
      {
        path: '/corporatecard',
        name: 'Corporate Cards',
        isBottomMenu: true,
        icon: '/assets/new-imgs/corporate_card.svg',
        component: './CorporateCard/index',
      },
      {
        path: '/payment/detail/:payId',
        hideInBreadcrumb: true,
        hideInMenu: true,
        name: 'paymentDetail',
        component: './PaymentDetail/index',
      },
      {
        path: '/help',
        name: 'help',
        isBottomMenu: true,
        icon: '/assets/new-imgs/icon_help.svg',
        component: './Help/index',
      },
      {
        component: '404',
      },
    ],
  },
];
