export const TAB_IDS = {
  ANNOUNCEMENTS: 'ANNOUNCEMENTS',
  ANNIVERSARY: 'ANNIVERSARY',
  IMAGES: 'IMAGES',
  BANNER: 'BANNER',
  POLL: 'POLL',
};

export const CELEBRATE_TYPE = {
  ANNIVERSARY: 'ANNIVERSARY',
  BIRTHDAY: 'BIRTHDAY',
  NEWJOINEE: 'NEWJOINEE',
};
