export const TAB_IDS = {
  ANNOUNCEMENTS: 'ANNOUNCEMENTS',
  ANNIVERSARY: 'ANNIVERSARY',
  IMAGES: 'IMAGES',
  BANNER: 'BANNER',
  POLL: 'POLL',
};

export const TAB_IDS_QUICK_LINK = {
  GENERAL: 'GENERAL',
  TIMEOFF: 'TIMEOFF',
  FORTIMEOFF: 'For Timeoff',
  GENERALTABNAME: 'General',
};

export const CELEBRATE_TYPE = {
  ANNIVERSARY: 'ANNIVERSARY',
  BIRTHDAY: 'BIRTHDAY',
  NEWJOINEE: 'NEWJOINEE',
};
