const PROCESS_STATUS_ARRAY = [
  'DRAFT',
  'FINAL-OFFER-DRAFT',

  'SENT-PROVISIONAL-OFFER',
  'ACCEPT-PROVISIONAL-OFFER',
  'RENEGOTIATE-PROVISONAL-OFFER',

  'PENDING-BACKGROUND-CHECK',
  'ELIGIBLE-CANDIDATE',
  'INELIGIBLE-CANDIDATE',

  'PENDING-APPROVAL-FINAL-OFFER',
  'APPROVED-FINAL-OFFER',

  'SENT-FINAL-OFFER',
  'ACCEPT-FINAL-OFFER',
  'RENEGOTIATE-FINAL-OFFERS', // add

  'DISCARDED-PROVISONAL-OFFER',
  'RECEIVED-SUBMITTED-DOCUMENTS',

  'REJECT-FINAL-OFFER-HR',
  'REJECT-FINAL-OFFER-CANDIDATE',

  'CLOSE',
];

const NEW_PROCESS_STATUS = {
  DRAFT: 'DRAFT',
  PROFILE_VERIFICATION: 'PROFILE_VERIFICATION',
  DOCUMENT_VERIFICATION: 'DOCUMENT_VERIFICATION',
  SALARY_NEGOTIATION: 'SALARY_NEGOTIATION',
  AWAITING_APPROVALS: 'AWAITING_APPROVALS',
  OFFER_RELEASED: 'OFFER_RELEASED',
  OFFER_ACCEPTED: 'OFFER_ACCEPTED',
  OFFER_REJECTED: 'OFFER_REJECTED',
  OFFER_WITHDRAWN: 'OFFER_WITHDRAWN',
};

const PROCESS_STATUS = {
  PROVISIONAL_OFFER_DRAFT: 'DRAFT',
  FINAL_OFFERS_DRAFT: 'FINAL-OFFER-DRAFT',

  SENT_PROVISIONAL_OFFERS: 'SENT-PROVISIONAL-OFFER',
  ACCEPTED_PROVISIONAL_OFFERS: 'ACCEPT-PROVISIONAL-OFFER',
  RENEGOTIATE_PROVISIONAL_OFFERS: 'RENEGOTIATE-PROVISONAL-OFFER',

  PENDING: 'PENDING-BACKGROUND-CHECK',
  ELIGIBLE_CANDIDATES: 'ELIGIBLE-CANDIDATE',
  INELIGIBLE_CANDIDATES: 'INELIGIBLE-CANDIDATE',

  SENT_FOR_APPROVAL: 'PENDING-APPROVAL-FINAL-OFFER',
  APPROVED_OFFERS: 'APPROVED-FINAL-OFFER',

  SENT_FINAL_OFFERS: 'SENT-FINAL-OFFER',
  ACCEPTED_FINAL_OFFERS: 'ACCEPT-FINAL-OFFER',
  RENEGOTIATE_FINAL_OFFERS: 'RENEGOTIATE-FINAL-OFFERS',

  PROVISIONAL_OFFERS: 'DISCARDED-PROVISONAL-OFFER',

  FINAL_OFFERS: 'FINAL-OFFERS',
  FINAL_OFFERS_HR: 'REJECT-FINAL-OFFER-HR',
  FINAL_OFFERS_CANDIDATE: 'REJECT-FINAL-OFFER-CANDIDATE',

  ALL: [
    'DRAFT',
    'FINAL-OFFER-DRAFT',
    'SENT-PROVISIONAL-OFFER',
    'ACCEPT-PROVISIONAL-OFFER',
    'RENEGOTIATE-PROVISONAL-OFFER',
    'PENDING-BACKGROUND-CHECK',
    'ELIGIBLE-CANDIDATE',
    'INELIGIBLE-CANDIDATE',
    'PENDING-APPROVAL-FINAL-OFFER',
    'APPROVED-FINAL-OFFER',
    'SENT-FINAL-OFFER',
    'ACCEPT-FINAL-OFFER',
    'RENEGOTIATE-FINAL-OFFERS',
    'DISCARDED-PROVISONAL-OFFER',
    'FINAL-OFFERS',
    'REJECT-FINAL-OFFER-HR',
    'REJECT-FINAL-OFFER-CANDIDATE',
  ],
};

const PROCESS_STATUS_TABLE_NAME = {
  DRAFT: 'Provisional Offer Drafts',
  'FINAL-OFFER-DRAFT': 'Final Offers Draft',

  'SENT-PROVISIONAL-OFFER': 'Sent Provisional Offers',
  'ACCEPT-PROVISIONAL-OFFER': 'Accepted Provisional Offers',
  'RENEGOTIATE-PROVISONAL-OFFER': 'Renegotiate Provisional Offers',

  'PENDING-BACKGROUND-CHECK': 'Pending',
  'ELIGIBLE-CANDIDATE': 'Eligible Candidates',
  'INELIGIBLE-CANDIDATE': 'Ineligible Candidates',

  'PENDING-APPROVAL-FINAL-OFFER': 'Sent For Approval',
  'APPROVED-FINAL-OFFER': 'Approved Offers',

  'SENT-FINAL-OFFER': 'Sent Final Offers',
  'ACCEPT-FINAL-OFFER': 'Accepted Final Offers',

  'DISCARDED-PROVISONAL-OFFER': 'Provisional Offers',

  'RENEGOTIATE-FINAL-OFFERS': 'Re-Negotiate Final Offers',

  'REJECT-FINAL-OFFER-HR': 'Final Offers',
  'REJECT-FINAL-OFFER-CANDIDATE': 'Final Offers',
};

export { PROCESS_STATUS_TABLE_NAME, PROCESS_STATUS_ARRAY, PROCESS_STATUS, NEW_PROCESS_STATUS };
