import { Row, Col } from 'antd';
import React, { PureComponent } from 'react';
import styles from './index.less';
import TypeRow from './TypeRow';

// const data = [
//   {
//     title: 'Bank Detail',
//     body: [
//       {
//         kind: 'Offer Letter',
//         files: [
//           {
//             fileName: 'Abc.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//           {
//             fileName: 'Cdf.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//         ],
//       },
//       {
//         kind: 'Offer Letter',
//         files: [
//           {
//             fileName: 'Abc.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//           {
//             fileName: 'Cdf.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//         ],
//       },
//     ],
//   },
//   {
//     title: 'Example 2',
//     body: [
//       {
//         kind: 'Offer Letter',
//         files: [
//           {
//             fileName: 'Abc.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//         ],
//       },
//       {
//         kind: 'Offer Letter',
//         files: [
//           {
//             fileName: 'Abc.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//           {
//             fileName: 'Cdf.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//           {
//             fileName: 'Abc.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//           {
//             fileName: 'Cdf.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//         ],
//       },
//     ],
//   },
//   {
//     title: 'Example 3',
//     body: [
//       {
//         kind: 'Offer Letter',
//         files: [
//           {
//             fileName: 'Abc.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//           {
//             fileName: 'Cdf.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//         ],
//       },
//       {
//         kind: 'Offer Letter',
//         files: [
//           {
//             fileName: 'Abc.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//           {
//             fileName: 'Cdf.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//         ],
//       },
//     ],
//   },
//   {
//     title: 'Example 4',
//     body: [
//       {
//         kind: 'Offer Letter',
//         files: [
//           {
//             fileName: 'Abc.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//           {
//             fileName: 'Cdf.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//         ],
//       },
//       {
//         kind: 'Offer Letter',
//         files: [
//           {
//             fileName: 'Abc.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//           {
//             fileName: 'Cdf.txt',
//             generatedBy: 'Terralogic',
//             date: '20/12/2020',
//           },
//         ],
//       },
//     ],
//   },
// ];

class InfoCollapseType2 extends PureComponent {
  render() {
    const { data = [] } = this.props;
    return (
      <div className={styles.InfoCollapseType2}>
        <div className={styles.tableTitle}>
          <span>{data.title}</span>
        </div>
        <Row className={styles.columnName}>
          <Col span={8}>Type</Col>
          <Col span={7}>Generated By</Col>
          <Col span={7}>Date</Col>
          <Col className={styles.status} span={2}>
            Status
          </Col>
        </Row>
        <div className={styles.tableOfContents}>
          <TypeRow data={data.body} />
        </div>
      </div>
    );
  }
}

export default InfoCollapseType2;
