import { Row, Col } from 'antd';
import React, { PureComponent } from 'react';
import styles from './index.less';
import TypeRow from './TypeRow';

class InfoCollapseType2 extends PureComponent {
  render() {
    const { data = [] } = this.props;
    return (
      <div className={styles.InfoCollapseType2}>
        <div className={styles.tableTitle}>
          <span>Bank Details</span>
        </div>
        <Row className={styles.columnName}>
          <Col span={8}>Type</Col>
          <Col span={7}>Generated By</Col>
          <Col span={7}>Date</Col>
          <Col className={styles.status} span={2}>Status</Col>
        </Row>
        <div className={styles.tableOfContents}>
          <TypeRow data={data} />
        </div>
      </div>
    )
  }
}

export default InfoCollapseType2;