import React, { PureComponent } from 'react';
import InfoCollapseType2 from './InfoCollapseType2';
import ViewDocument from './ViewDocument';
import styles from './index.less';

const data = [
  {
    title: 'Bank Detail',
    type: 1, // generated by
    body: [
      {
        kind: 'Offer Letter',
        files: [
          {
            id: 1,
            fileName: 'Abc.pdf',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
          {
            id: 2,
            fileName: 'Cdf documents.pdf',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
        ],
      },
      {
        kind: 'Offer Letter',
        files: [
          {
            id: 3,
            fileName: 'Abc documents.pdf',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
          {
            id: 4,
            fileName: 'Cdf.pdf',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
        ],
      },
    ],
  },
  {
    title: 'Example 2',
    type: 2, // uploaded by
    body: [
      {
        kind: 'Offer Letter Document',
        files: [
          {
            id: 5,
            fileName: 'Abc documents.pdf',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
          {
            id: 6,
            fileName: 'Cdf.pdf',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
          {
            id: 7,
            fileName: 'Abc documents.pdf',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
          {
            id: 8,
            fileName: 'Cdf.pdf',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
        ],
      },
    ],
  },
];

class Documents extends PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      isViewingDocument: false,
      selectedFile: [],
    };
  }

  onBackClick = () => {
    this.setState({
      isViewingDocument: false,
    });
  };

  onFileClick = (value) => {
    console.log('file: ', value);
    // eslint-disable-next-line array-callback-return
    data.some((x) => {
      // eslint-disable-next-line array-callback-return
      x.body.some((y) => {
        // eslint-disable-next-line array-callback-return
        y.files.some((z) => {
          if (z.id === value) {
            this.setState({
              isViewingDocument: true,
              selectedFile: z,
            });
            return true;
          }
          return false;
        });
      });
    });
  };

  render() {
    const { isViewingDocument, selectedFile } = this.state;
    return (
      <div className={styles.Documents}>
        {isViewingDocument ? (
          <ViewDocument selectedFile={selectedFile} onBackClick={this.onBackClick} />
        ) : (
          data.map((value) => <InfoCollapseType2 onFileClick={this.onFileClick} data={value} />)
        )}
      </div>
    );
  }
}

export default Documents;
