import React, { PureComponent } from 'react';
import InfoCollapseType2 from './InfoCollapseType2';
import ViewDocument from './ViewDocument';
import styles from './index.less';

const data = [
  {
    title: 'Bank Detail',
    type: 1, // generated by
    body: [
      {
        kind: 'Offer Letter',
        files: [
          {
            fileName: 'Abc.txt',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
          {
            fileName: 'Cdf.txt',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
        ],
      },
      {
        kind: 'Offer Letter',
        files: [
          {
            fileName: 'Abc.txt',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
          {
            fileName: 'Cdf.txt',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
        ],
      },
    ],
  },
  {
    title: 'Example 2',
    type: 2, // uploaded by
    body: [
      {
        kind: 'Offer Letter',
        files: [
          {
            fileName: 'Abc.txt',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
          {
            fileName: 'Cdf.txt',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
          {
            fileName: 'Abc.txt',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
          {
            fileName: 'Cdf.txt',
            generatedBy: 'Terralogic',
            date: '20/12/2020',
          },
        ],
      },
    ],
  },
];

class Documents extends PureComponent {
  render() {
    return (
      <div className={styles.Documents}>
        {data.map((value) => (
          <InfoCollapseType2 data={value} />
        ))}
        <ViewDocument />
      </div>
    );
  }
}

export default Documents;
