const rookieList = [
  {
    key: '1',
    rookieId: '#16003134',
    isNew: true,
    rookieName: 'Matt Wagoner',
    position: 'Sr. UX Designer',
    location: 'Mumbai',
    comments: 'Passport submission pending …',
    dateSent: '29th Sept, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '2',
    rookieId: '#18001829',
    isNew: true,
    rookieName: 'JT Grauke',
    position: 'UI Designer',
    location: 'Mumbai',
    comments: 'Fake eligibility documents',
    dateSent: '3rd Oct, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '3',
    rookieId: '#16210862',
    isNew: true,
    rookieName: 'Ryan Jhonson',
    position: 'Sr. UI Designer',
    location: 'Chennai',
    comments: 'Fake eligibility documents',
    dateSent: '30th Nov, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '4',
    rookieId: '#10928389',
    isNew: true,
    rookieName: 'Billy Hoffman',
    position: 'Illustrator',
    location: 'Mumbai',
    comments: 'Fake eligibility documents',
    dateSent: '29th Sept, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '5',
    rookieId: '#16013134',
    rookieName: 'Karthik Naren',
    position: 'Jr. UI Designer',
    location: 'Dubai',
    comments: 'Eligibility date expireds',
    dateSent: '12th Jan, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '6',
    rookieId: '#16211862',
    rookieName: 'Ema Drek',
    position: 'Sr. UX Designer',
    location: 'Bangalore',
    comments: 'Eligibility date expired',
    dateSent: '09th Aug, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '7',
    rookieId: '#11928389',
    rookieName: 'Suraj Bhatt',
    position: 'Sr. Illustrator',
    location: 'Dubai',
    comments: 'Fake eligibility documents',
    dateSent: '19th June, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '8',
    rookieId: '#10978389',
    rookieName: 'Siddartha',
    position: 'Sr. Illustrator',
    location: 'Dubai',
    comments: 'Fake eligibility documents',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '9',
    rookieId: '#10926389',
    rookieName: 'Suraj Bhatt',
    position: 'Sr. Illustrator',
    location: 'Dubai',
    comments: 'Eligibility date expired',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '10',
    rookieId: '#10928089',
    rookieName: 'Suraj Bhatt',
    position: 'Sr. Illustrator',
    location: 'Dubai',
    comments: 'Eligibility date expired',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  // Clone
  {
    key: '11',
    rookieId: '#26003134',
    rookieName: 'Matt Wagoner',
    position: 'Sr. UX Designer',
    location: 'Mumbai',
    comments: 'Passport submission pending …',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '12',
    rookieId: '#28001829',
    isNew: true,
    rookieName: 'JT Grauke',
    position: 'UI Designer',
    location: 'Mumbai',
    comments: 'Fake eligibility documents',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '13',
    rookieId: '#26210862',
    rookieName: 'Ryan Jhonson',
    position: 'Sr. UI Designer',
    location: 'Chennai',
    comments: 'Fake eligibility documents',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '14',
    rookieId: '#20928389',
    rookieName: 'Billy Hoffman',
    position: 'Illustrator',
    location: 'Mumbai',
    comments: 'Fake eligibility documents',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '15',
    rookieId: '#26013134',
    rookieName: 'Karthik Naren',
    position: 'Jr. UI Designer',
    location: 'Dubai',
    comments: 'Eligibility date expireds',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '16',
    rookieId: '#26211862',
    isNew: true,
    rookieName: 'Ema Drek',
    position: 'Sr. UX Designer',
    location: 'Bangalore',
    comments: 'Eligibility date expired',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '17',
    rookieId: '#21928389',
    isNew: true,
    rookieName: 'Suraj Bhatt',
    position: 'Sr. Illustrator',
    location: 'Dubai',
    comments: 'Fake eligibility documents',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '18',
    rookieId: '#20978389',
    rookieName: 'Siddartha',
    position: 'Sr. Illustrator',
    location: 'Dubai',
    comments: 'Fake eligibility documents',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '19',
    rookieId: '#20926389',
    rookieName: 'Suraj Bhatt',
    position: 'Sr. Illustrator',
    location: 'Dubai',
    comments: 'Eligibility date expired',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
  {
    key: '20',
    rookieId: '#20928089',
    isNew: true,
    rookieName: 'Suraj Bhatt',
    position: 'Sr. Illustrator',
    location: 'Dubai',
    comments: 'Eligibility date expired',
    dateSent: '23th May, 2020',
    dateJoin: '29th Sept, 2020',
  },
];

const employeeList = rookieList.filter((rookie) => rookie.isNew != true);

const onboard = {
  namespace: 'onboard',
  state: {
    onboardingOverview: {
      pendingEligibilityChecks: {
        sentEligibilityForms: null,
        receivedSubmittedDocuments: null,
      },
      eligibleCandidates: rookieList,
      ineligibleCandidates: rookieList,
      provisionalOffers: {
        sentProvisionalOffers: rookieList,
        receivedProvisionalOffers: rookieList,
      },
      discardedProvisionalOffers: employeeList,
      awaitingApprovals: {
        approvedFinalOffers: employeeList,
        pendingApprovals: employeeList,
        rejectFinalOffer: employeeList,
      },
      finalOffers: {
        acceptedFinalOffers: employeeList,
        sentFinalOffers: rookieList,
      },
      finalOfferDrafts: employeeList,
      discardedFinalOffers: rookieList,
    },
    settings: {},
    customFields: {},
  },
  effects: {
    // *fetchEmployeeType(_, { call, put }) {
    //   try {
    //     const response = yield call(EmployeeTypeFilter);
    //     const { statusCode, data: employeetype = [] } = response;
    //     if (statusCode !== 200) throw response;
    //     yield put({ type: 'saveEmployeeType', payload: { employeetype } });
    //   } catch (errors) {
    //     dialog(errors);
    //   }
    // },
  },
  reducers: {
    save(state, action) {
      return {
        ...state,
        ...action.payload,
      };
    },
  },
};
export default onboard;
