export default {
  'pages.employeeProfile.documents.infoCollapseType2.type': 'Type',
  'pages.employeeProfile.documents.infoCollapseType2.generatedBy': 'Generated By',
  'pages.employeeProfile.documents.infoCollapseType2.date': 'Date',
  'pages.employeeProfile.documents.infoCollapseType2.status': 'Status',
};
