export default {
  'pages.employeeProfile.generalInfoTab': 'General Info',
  'pages.employeeProfile.employmentAndCompensationTab': 'Employment & Compensation',
  'pages.employeeProfile.performanceHistoryTab': 'Performance History',
  'pages.employeeProfile.accountsAndPaychecksTab': 'Accounts and Paychecks',
  'pages.employeeProfile.documentsTab': 'Documents',
  'pages.employeeProfile.workEligibilityAndI-9Tab': 'Work Eligibility & I-9',
  'pages.employeeProfile.timeAndSchedulingTab': 'Time & Scheduling',
  'pages.employeeProfile.benefitPlansTab': 'Benefit Plans',

  'pages.employeeProfile.putOnLeave': 'Put on Leave (PWP)',
  'pages.employeeProfile.raiseTermination': 'Raise Termination',
  'pages.employeeProfile.requestDetails': 'Request Details',
  'pages.employeeProfile.actionMenu': 'Action',

  'pages.employeeProfile.location': 'Location',
  'pages.employeeProfile.joinedOn': 'Joined on',

  'pages.employeeProfile.documents.infoCollapseType2.type': 'Type',
  'pages.employeeProfile.documents.infoCollapseType2.generatedBy': 'Generated By',
  'pages.employeeProfile.documents.infoCollapseType2.date': 'Date',
  'pages.employeeProfile.documents.infoCollapseType2.status': 'Status',
};
